CREATE TABLE BOOKDB.USER(
    ID NUMBER(20,0) NOT NULL,
    ROLE VARCHAR(64) NOT NULL,
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL,
    ENABLED NUMBER(1,0) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BOOKDB.SHARED(
    USER_ID NUMBER(20,0) NOT NULL,
    ALBUM_ID NUMBER(20,0) NOT NULL,
    PRIVILEGE VARCHAR(64) NOT NULL,
    PRIMARY KEY (USER_ID, ALBUM_ID)
);